### PR TITLE
Android implementation

### LINKED ISSUE #3: Android support
Currently the repo supports iOS only.

[Over on Discord](https://discord.com/channels/826071713426178078/925778689008996412/1166370416982491156), Nick wrote this which might be helpful when working on Android support:

> Yea! I've done this before for a client project and the integration looks a lot like the integration in the elem cli: https://github.com/elemaudio/elementary/blob/main/cli/Realtime.cpp
Obviously it's your choice how you want to deal with the driver but I highly recommend miniaudio, as used in that cli example. For a react-native integration it's basically the same: make a native module that has methods for opening and closing the device, then configure an elem runtime instance to write the buffers from the device, and add another method for the applyInstructions step. Then from javascript you can (1) open the device, (2) make a custom renderer that sends its payloads to the applyInstructions hook, and then when the app closes (3) close the device

If someone gets it working nice with miniaudio on Android, I might end up throwing away the current CoreAudio stuff and using miniaudio on iOS too.

cc @txbrown

### PR DESCRIPTION
**Pull request by txbrown**
## Describe your changes

This PR adds support for Elementary-Audio in React-Native Android platform.
It uses `miniaudio` library as the audio driver.

Other changes:
- Moved the shared C++ vendor files into `cpp/...`
- Updated `elementary` submodule (this was not intentional initially but now it has latest with sparseq2 for example)
- Bumped iOS min deployment target which introduces compatibility with C++ features used in latest elementary codebase

Closes #3

### CODE REVIEW

**Comment by txbrown** [comment]
@tamlyn could you please review this PR?

**Comment by tamlyn** [comment]
Sorry! Yes, I'll take a look ASAP.

**Comment by txbrown** [comment]
Hey @tamlyn have tou had a chance to review this?

**Comment by tamlyn** [comment]
Aaaaargh! Ok I'm setting a reminder in my phone...

**Review by tamlyn — APPROVED** [review]
Awesome!

**Comment by ebenoist** [comment]
Any special setup for local dev with Android?

**Pull request merged**
